### ISSUE TITLE
Wrong Assignment

### ISSUE THREAD

**Issue by Anuj040** [mamo3gr/partial_label_masking#2]
https://github.com/mamo3gr/partial_label_masking/blob/2eca2cb09fb15075d317ad7fdaab296b2395482a/src/plm_keras.py#L45

I believe the assignment is wrong. It should be as follows:
```self.hist_neg_pred += hist_neg_pred```

**Comment by mamo3gr** [comment]
@Anuj040 Thank you very much for pointing out the bug!
I have fixed it by https://github.com/mamo3gr/partial_label_masking/pull/3.
